[package]
name = "timewall"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.64"
base64 = "0.13.0"
blake3 = "1.3.1"
chrono = "0.4.22"
clap = { version = "3.2.20", features = ["derive"] }
directories = "4.0.1"
env_logger = "0.9.0"
itertools = "0.10.5"
libheif-rs = "0.15.0"
log = "0.4.17"
ordered-float = { version = "3.2.0", features = ["serde"] }
plist = "1.3.1"
png = "0.17.6"
serde = { version = "1.0.144", features = ["derive"] }
sun = "0.2.0"
toml = "0.5.9"
xml-rs = "0.8.4"

[dev-dependencies]
assert_fs = "1.0.7"
predicates = "2.1.1"
rstest = "0.15.0"
